# Project Name
TARGET = pluck1

# Sources
CPP_SOURCES = pluck1.cpp

# Library Locations
LIBDAISY_DIR ?= ../../lib/libDaisy
DAISYSP_DIR ?= ../../lib/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

all: build program-dfu
